epam/ai-dial-helm

.github/workflows/release.yaml
charts/dial/.helmignore
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/README.md.gotmpl
charts/dial/ci/fixtures-values.yaml
charts/dial/templates/NOTES.txt
charts/dial/templates/_helpers.tpl
charts/dial/templates/extra-list.yaml
charts/dial/values.yaml
ct.yaml

- fixes none
The initial creation of dial helm chart

feat: add dial chart

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/README.md.gotmpl
charts/dial/examples/README.md
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/README.md
charts/dial/examples/generic/simple/values.yaml

- Updated chart dependencies
- Added AI DIAL Generic Installation Simple Guide, AI DIAL AWS Installation Simple Guide & created examples file structure

chore: update chart dependencies

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/README.md
charts/dial/examples/generic/simple/values.yaml
charts/dial/templates/NOTES.txt
charts/dial/templates/_helpers.tpl
charts/dial/values.yaml

This is a release of **dial** chart
- new versions
- update **dial-core** subchart version
- add **dial-core** mandatory encryption values validation

feat: dial release 1.2.0

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/README.md
charts/dial/examples/generic/simple/values.yaml

- fixes https://github.com/epam/ai-dial-chat/issues/427
- Rename environment variable `OPENAI_API_HOST` to `DIAL_API_HOST`
- Rename environment variable `OPENAI_API_KEY` to `DIAL_API_KEY`
- Rename environment variable `OPENAI_API_VERSION` to `DIAL_API_VERSION`

chore: rename chat variables from OPENAI_ to DIAL_

---

README.md
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/README.md
charts/dial/examples/generic/simple/values.yaml
charts/dial/values.yaml

This is a release of dial chart
- new application versions
- chat env variables renamed

feat: dial release 1.3.0

---

charts/dial/Chart.yaml
charts/dial/README.md

- Update dependency **dial-core** helm chart to `1.2.0`
- Update dependency **keycloak** helm chart to `16.1.7`
- Update dependency **common** helm chart to `2.14.1`
- templated locally

chore: update dial-core, keycloak, common helm chart dependencies

---

charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/README.md
charts/dial/examples/generic/simple/values.yaml

- Updated example helm values file to align with core version 0.7.x

chore: Upadate helm examples for dial core 0.7.X

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/README.md
charts/dial/examples/generic/simple/values.yaml
charts/dial/values.yaml

- new application versions
- update examples

feat: dial release 1.4.0

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/azure/simple/README.md
charts/dial/examples/azure/simple/values.yaml
charts/dial/examples/gcp/simple/README.md
charts/dial/examples/gcp/simple/values.yaml
charts/dial/values.yaml

- bump dial-core chart with Redis enabled by default
- update dial helm examples by @alexey-ban in #22 

feat!: release 1.5

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/azure/simple/README.md
charts/dial/examples/gcp/simple/README.md
charts/dial/examples/generic/simple/README.md
charts/dial/values.yaml

- Fixes NGINX controller link in examples description
- bumps **ai-dial-chat** and **ai-dial-core** versions

chore: update dial with patch 

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/values.yaml

Fix default container image registry and repository for ai-dial-core logger values.

chore: Update image registry for dial-core logger component

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/values.yaml

- edit healthcheck path for `ai-dial-chat-themes` in `examples/aws/simple`

feat: DIAL release 1.7

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: DIAL release 1.8

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/templates/deployment.yaml
charts/dial-core/templates/hpa.yaml
charts/dial-core/values.yaml
charts/dial-extension/Chart.yaml
charts/dial-extension/README.md
charts/dial-extension/templates/deployment.yaml
charts/dial-extension/templates/hpa.yaml
charts/dial-extension/values.yaml

HPA support has been added for sub-charts.
No

chore: add hpa support to subcharts

---

charts/dial/Chart.yaml
charts/dial/README.md

chore: add hpa to dial chart

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: DIAL release 1.9

---

.github/workflows/pr-title-check.yml
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/complete/README.md
charts/dial/examples/aws/complete/values.yaml
charts/dial/examples/aws/simple/README.md
charts/dial/examples/aws/simple/values.yaml
charts/dial/values.yaml

feat: DIAL release 1.10

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feature: DIAL release 1.11

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/complete/README.md
charts/dial/examples/aws/complete/values.yaml
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/generic/simple/values.yaml
charts/dial/values.yaml
ct.yaml

feat: DIAL release 1.12

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: DIAL release 1.13

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

fix: DIAL release 1.13

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/ci/fixtures-values.yaml
charts/dial-core/values.yaml

feat: add dial-core probes

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
Bump patch versions for **core** and **chat** applications, no configuration changes.

chore: bump patch versions for core and chat applications

---

charts/dial-extension/Chart.yaml
charts/dial-extension/README.md
charts/dial-extension/templates/deployment.yaml
charts/dial-extension/values.yaml

feat: add custom probes to dial-extension chart

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/templates/deployment.yaml
charts/dial-core/values.yaml

feat: add custom probes to dial-core chart

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: add custom probes to dial chart

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: DIAL release 1.14

---

charts/dial-extension/README.md
charts/dial-extension/README.md.gotmpl

chore: fix install command in dial-extension README

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: add adapter-dial to dial chart

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/gcp/complete/README.md
charts/dial/examples/gcp/complete/values.yaml
charts/dial/values.yaml

- fixes #
- feat: add adapter-dial to dial chart in #78
- fix: gcp complete example and core gcs fix in #77

feat: DIAL release 1.15.0

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
.github/workflows/sync-readme.yaml
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

feat: DIAL release 1.16

---

charts/dial/examples/aws/complete/values.yaml
charts/dial/examples/aws/simple/values.yaml

- fixes #
When using an existing URL for an endpoint, a newly deployed DIAL in AWS EKS returns an HTTP 404 error for any actions on that model.

fix: Corrected sub-path for model Anthropic (Claude) to match current state

---

charts/dial/examples/azure/complete/README.md
charts/dial/examples/azure/complete/values.yaml
charts/dial/examples/gcp/complete/values.yaml

chore: azure complete example

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/complete/values.yaml
charts/dial/examples/aws/simple/values.yaml
charts/dial/examples/azure/complete/README.md
charts/dial/examples/azure/complete/values.yaml
charts/dial/examples/gcp/complete/values.yaml
charts/dial/values.yaml

- fixes #
- bump chart dependencies (dial-core, dial-extension) versions
- fix: Corrected sub-path for model Anthropic (Claude) to match current state (#65)
- feat: azure complete example (#80)

feat: DIAL release 1.17

---

.github/workflows/lint-test.yaml
.github/workflows/pr-title-check.yml
.github/workflows/release.yaml
.github/workflows/sync-readme.yaml
charts/dial-extension/Chart.yaml
charts/dial-extension/README.md

- Bump bitnami-common helm chart version (must be aligned with all other dependency helm charts from bitnami on a higher level).
No breaking changes expected, therefore bumping minor only.

feat: bump bitnami-common dependency in dial-extension chart

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/README.md.gotmpl
charts/dial/values.yaml

- fixes #
- bump chart dependencies (common, dial-core, dial-extension) versions
Bumping the major version to highlight Redis upgrade in `dial-core` helm chart only. No actions required.

feat: DIAL release 1.18

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

chore: bump patch version for openai adapter

---

charts/dial/examples/aws/complete/README.md
charts/dial/examples/aws/complete/values.yaml

chore: remove reference to secret store

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/aws/complete/README.md
charts/dial/examples/aws/complete/values.yaml
charts/dial/examples/azure/complete/README.md
charts/dial/examples/azure/simple/README.md
charts/dial/values.yaml

- fixes #
- feat: bump application versions
- chore: fix typos in examples/azure (#95)
- chore: remove reference to secret store in examples/aws (#100)

feat: DIAL release 1.19

---

.github/workflows/lint-test.yaml

chore: bump helm/kind-action from 1.10.0 to 1.11.0 REVERT

---

.github/workflows/lint-test.yaml
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- feat: bump application versions

feat: DIAL release 1.20

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- feat: bump application versions
- ai-dial-adapter-bedrock: 0.20.0 --> 0.21.0
- ai-dial-adapter-openai: 0.18.0 --> 0.19.0
- ai-dial-adapter-vertexai: 0.14.0 --> 0.15.0
- ai-dial-adapter-dial: 0.3.1 --> 0.4.0
- ai-dial-analytics-realtime: 0.8.0 --> 0.9.0
- ai-dial-chat: 0.22.0 --> 0.23.0
- ai-dial-core: 0.21.0 --> 0.22.0

feat: DIAL release 1.21

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-extension/Chart.yaml
charts/dial-extension/README.md

- fixes #
- bump bitnami/common helm chart dependency from `2.26.0` to `2.29.0`
- bump bitnami/redis-cluster helm chart dependency from `11.0.6` to `11.4.0`

feat: bump bitnami/common, bitnami/redis-cluster helm chart versions in dial-extension, dial-core charts

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/README.md.gotmpl
charts/dial/values.yaml

- fixes #
- `bitnami/keycloak` Helm chart version bumped from `16.1.7` to `24.4.3`
- `keycloak` version bumped from `22.0.3` to `26.0.8`
- `bitnami/postgresql` Helm chart from `12.12.9` to `16.4.3`
- `postgresql` version bumped from `15.4.0` to `17.2.0`
- `bitnami/common` helm chart version bumped from `2.26.0` to `2.29.0`

feat!: bump bitnami/keycloak, bitnami/common helm chart versions

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- feat: bump application versions:
- ai-dial-core: 0.22.0 => 0.23.0
- ai-dial-chat: 0.23.0 => 0.24.0
- ai-dial-adapter-openai: 0.19.0 => 0.20.0
- ai-dial-adapter-bedrock: 0.21.0 => 0.22.0
- ai-dial-adapter-vertexai: 0.15.0 => 0.17.0 

feat: DIAL release 1.22

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- feat: bump application versions:
- ai-dial-core: 0.23.0 => 0.24.0
- ai-dial-chat: 0.24.0 => 0.25.0
- ai-dial-adapter-openai: 0.20.0 => 0.21.0
- ai-dial-adapter-vertexai: 0.17.0 => 0.17.2

feat: DIAL release 1.23

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- ai-dial-core: 0.24.0 => 0.25.0
- ai-dial-chat: 0.25.0 => 0.26.0
- ai-dial-adapter-openai: 0.21.0 => 0.22.0
- ai-dial-adapter-bedrock: 0.22.0 => 0.23.0
- ai-dial-adapter-dial: 0.4.0 => 0.5.0

feat: DIAL release 1.24

---

charts/dial-extension/templates/deployment.yaml

chore: align imagePullPolicy quoting in dial-extension

---

charts/dial-extension/Chart.yaml
charts/dial-extension/README.md
charts/dial-extension/templates/deployment.yaml

fix: dial-extension chart minor improvements

---

charts/dial-core/README.md
charts/dial-core/values.yaml

fix: logger.extraVolumeMounts default value from object to list

---

charts/dial-core/templates/deployment.yaml

- fixes #
- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/)

chore: align imagePullPolicy quoting in dial-core

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/templates/deployment.yaml
charts/dial-core/values.yaml

fix: dial-core chart minor improvements 

---

charts/dial/Chart.yaml
charts/dial/README.md

- fixes #
subcharts `dial-core`, `dial-extension` versions bumped

chore: bump dial-core, dial-extension subchart versions

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/README.md.gotmpl
charts/dial/values.yaml

- fixes #
- #122
- fix: bump ai-dial-chat version to `0.26.3`
- #125
- fix: update README with instructions to add "basic" to defaultClientScopes in Keycloak configuration

feat: DIAL patch release 1.24.1

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- ai-dial-core: 0.25.0 => 0.26.0
- ai-dial-chat: 0.26.3 => 0.27.1
- ai-dial-adapter-openai: 0.22.0 => 0.23.0
- ai-dial-adapter-bedrock: 0.23.0 => 0.24.0
- ai-dial-adapter-vertexai: 0.17.2 => 0.18.0
fix: run ai-dial-core logger without root privileges

feat: DIAL release 1.25

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- ai-dial-core: 0.26.0 => 0.27.0
- ai-dial-chat: 0.27.1 => 0.28.1
- ai-dial-adapter-openai: 0.23.0 => 0.24.0
- ai-dial-adapter-bedrock: 0.24.0 => 0.25.0
- ai-dial-adapter-vertexai: 0.18.0 => 0.19.0

feat: DIAL release 1.26

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- ai-dial-core: 0.27.0 => 0.28.0
- ai-dial-chat: 0.28.1 => 0.29.0
- ai-dial-adapter-openai: 0.24.0 => 0.25.0
- ai-dial-adapter-bedrock: 0.25.0 => 0.26.0
- ai-dial-adapter-vertexai: 0.19.0 => 0.20.0

feat: DIAL release 1.27

---

.github/workflows/lint-test.yaml
.github/workflows/pr-title-check.yml
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/gcp/complete/values.yaml
charts/dial/values.yaml

- fixes #
- ai-dial-chat: 0.29.1 => 0.30.0
- ai-dial-adapter-bedrock: 0.26.0 => 0.27.0
- ai-dial-adapter-vertexai: 0.20.0 => 0.21.0
- ai-dial-auth-helper: 0.3.0 => 0.4.0
chore: include dependabot PRs:
- https://github.com/epam/ai-dial-helm/pull/140
- https://github.com/epam/ai-dial-helm/pull/141

feat: DIAL release 1.28

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/examples/azure/complete/README.md
charts/dial/examples/azure/complete/values.yaml
charts/dial/values.yaml

- fixes #
- Bump application versions:
- ai-dial-core: 0.28.0 => 0.29.0
- ai-dial-chat: 0.30.0 => 0.31.1
- ai-dial-chat-themes: 0.9.1 => 0.10.0
- ai-dial-adapter-openai: 0.25.0 => 0.26.0
- ai-dial-adapter-bedrock: 0.27.0 => 0.28.0
- ai-dial-adapter-vertexai: 0.21.0 => 0.22.0
- ai-dial-adapter-dial: 0.5.0 => 0.6.0
- Update docs for Azure Redis Cache authentication (see https://github.com/epam/ai-dial-helm/pull/144)

feat: DIAL release 1.29

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- Bump application versions:
- ai-dial-core:  0.29.0 => 0.30.0
- ai-dial-chat: 0.31.1 => 0.32.0
- ai-dial-chat-themes: 0.10.0 => 0.10.0
- ai-dial-adapter-openai: 0.26.0 => 0.27.0
- ai-dial-adapter-bedrock: 0.28.0 => 0.29.0
- ai-dial-adapter-vertexai: 0.22.0 => 0.23.0
- ai-dial-adapter-dial: 0.6.0 => 0.7.0

feat: DIAL release 1.30

---

charts/dial-admin/Chart.yaml
charts/dial-admin/README.md
charts/dial-admin/templates/_helpers.tpl
charts/dial-admin/templates/backend/deployment.yaml

fix: database environment variables indentation for DIAL Admin

---

charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/values.yaml

- fixes #
Set `bitnamilegacy/redis-cluster` repository instead of `bitnami/redis-cluster` provided in their defaults.
Bitnami is moving towards monetizing its image catalog and [will remove](https://github.com/bitnami/charts/issues/35164) all versions besides `latest`.

fix: use bitnamilegacy container repo for dial-core redis

---

charts/dial-admin/Chart.yaml
charts/dial-admin/README.md
charts/dial-admin/values.yaml

- fixes #
Set `bitnamilegacy/postgres` repository instead of `bitnami/postgres` provided in their defaults.
Bitnami is moving towards monetizing its image catalog and [will remove](https://github.com/bitnami/charts/issues/35164) all versions besides `latest`.

fix: use bitnamilegacy container repo for dial-admin postgres

---

.github/workflows/pr-title-check.yml
charts/dial-admin/Chart.yaml
charts/dial-admin/README.md
charts/dial-admin/values.yaml
charts/dial-core/Chart.yaml
charts/dial-core/README.md
charts/dial-core/values.yaml
charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- Bump application versions:
- ai-dial-core: 0.32.0 => 0.33.0
- ai-dial-chat: 0.34.0 => 0.35.0
- ai-dial-adapter-openai: 0.29.0 => 0.30.0
- ai-dial-adapter-bedrock: 0.31.0 => 0.32.0
- ai-dial-adapter-vertexai: 0.25.0 => 0.26.0
- ai-dial-adapter-dial: 0.7.0 => 0.8.0
- Switch redis-cluster and keycloak to Bitnami "legacy" repository (see [Bitnami announcement](https://github.com/bitnami/charts/issues/35164) for details)

feat: DIAL release 1.33

---

charts/dial/Chart.yaml
charts/dial/README.md

feat: dial patch release logger prefix templating

---

charts/dial/Chart.yaml
charts/dial/README.md
charts/dial/values.yaml

- fixes #
- bump application versions:
- ai-dial-core: 0.33.0 => 0.34.0
- ai-dial-chat: 0.35.0 => 0.36.0
- ai-dial-adapter-openai: 0.30.0 => 0.31.0
> [!tip]
> From now on, ai-dial-core is using Java 21, which brings [virtual threads](https://docs.oracle.com/en/java/javase/21/core/virtual-threads.html). Add `aidial.asyncTaskExecutor.useVirtualThreads="false"` to `core.env` values to keep previous behavior.

feat: DIAL release 1.34
